// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328144226_FixRowVersionValueGeneration")]
    partial class FixRowVersionValueGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Computers.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("primeiroacesso");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("segundoacesso");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OperatingSystem");

                    b.HasKey("Id")
                        .HasName("pk_computers");

                    b.ToTable("Computers", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_local_users");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_local_users_username");

                    b.ToTable("local_users", (string)null);
                });

            modelBuilder.Entity("Domain.vault.ADMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Permission")
                        .HasColumnType("integer")
                        .HasColumnName("permission");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_id");

                    b.HasKey("Id")
                        .HasName("pk_vault_ad_map");

                    b.HasIndex("VaultId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_vault_ad_map_vault_id_group_id");

                    b.HasIndex("VaultId", "Permission", "IsActive")
                        .HasDatabaseName("ix_vault_ad_map_vault_id_permission_is_active");

                    b.HasIndex("VaultId", "IsActive", "Permission", "CreatedAt")
                        .HasDatabaseName("ix_vault_ad_map_vault_id_is_active_permission_created_at");

                    b.ToTable("vault_ad_map", (string)null);
                });

            modelBuilder.Entity("Domain.vault.Secret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_id");

                    b.HasKey("Id")
                        .HasName("pk_vault_secrets");

                    b.HasIndex("VaultId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vault_secrets_vault_id_name");

                    b.ToTable("vault_secrets", (string)null);
                });

            modelBuilder.Entity("Domain.vault.SecretAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("SecretName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("secret_name");

                    b.Property<Guid?>("VaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_id");

                    b.HasKey("Id")
                        .HasName("pk_vault_secret_audit");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_vault_secret_audit_action");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_vault_secret_audit_occurred_at_utc");

                    b.HasIndex("VaultId", "SecretName", "OccurredAtUtc")
                        .HasDatabaseName("ix_vault_secret_audit_vault_id_secret_name_occurred_at_utc");

                    b.ToTable("vault_secret_audit", (string)null);
                });

            modelBuilder.Entity("Domain.vault.SecretVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("CipherText")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("cipher_text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset?>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("KeyReference")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("key_reference");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("uuid")
                        .HasColumnName("secret_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_vault_secret_versions");

                    b.HasIndex("SecretId", "Expires")
                        .HasDatabaseName("ix_vault_secret_versions_secret_id_expires");

                    b.HasIndex("SecretId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_vault_secret_versions_secret_id_version");

                    b.HasIndex("SecretId", "IsRevoked", "Version")
                        .HasDatabaseName("ix_vault_secret_versions_secret_id_is_revoked_version");

                    b.ToTable("vault_secret_versions", (string)null);
                });

            modelBuilder.Entity("Domain.vault.Vault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowMultiFactorAuthentication")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_multi_factor_authentication");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("EncryptionPolicy")
                        .HasColumnType("integer")
                        .HasColumnName("encryption_policy");

                    b.Property<int>("Environment")
                        .HasColumnType("integer")
                        .HasColumnName("environment");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group");

                    b.Property<string>("KeyReference")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("key_reference");

                    b.Property<DateTimeOffset?>("LastRotation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rotation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<bool>("RequireMultiFactorAuthentication")
                        .HasColumnType("boolean")
                        .HasColumnName("require_multi_factor_authentication");

                    b.Property<int>("RotationPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("rotation_period");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_vault");

                    b.HasIndex("Group")
                        .HasDatabaseName("ix_vault_group");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vault_tenant_id_name");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_vault_tenant_id_slug");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_vault_tenant_id_status");

                    b.ToTable("vault", (string)null);
                });

            modelBuilder.Entity("Domain.vault.VaultMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ComputerId")
                        .HasColumnType("integer")
                        .HasColumnName("computer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_id");

                    b.HasKey("Id")
                        .HasName("pk_vault_machines");

                    b.HasIndex("ComputerId")
                        .HasDatabaseName("ix_vault_machines_computer_id");

                    b.HasIndex("VaultId", "ComputerId")
                        .IsUnique()
                        .HasDatabaseName("ix_vault_machines_vault_id_computer_id");

                    b.HasIndex("VaultId", "CreatedAt")
                        .HasDatabaseName("ix_vault_machines_vault_id_created_at");

                    b.HasIndex("VaultId", "Status")
                        .HasDatabaseName("ix_vault_machines_vault_id_status");

                    b.HasIndex("VaultId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_vault_machines_vault_id_status_created_at");

                    b.ToTable("vault_machines", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Security.NonceStoreEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("NonceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nonce_hash");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_nonce_store_entries");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_nonce_store_entries_expires_at_utc");

                    b.HasIndex("Scope", "NonceHash")
                        .IsUnique()
                        .HasDatabaseName("ix_nonce_store_entries_scope_nonce_hash");

                    b.ToTable("nonce_store_entries", (string)null);
                });

            modelBuilder.Entity("Domain.Computers.Computer", b =>
                {
                    b.OwnsOne("Domain.Computers.Bios", "Bios", b1 =>
                        {
                            b1.Property<int>("ComputerId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Serial")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("BiosSerial");

                            b1.HasKey("ComputerId");

                            b1.ToTable("Computers");

                            b1.WithOwner()
                                .HasForeignKey("ComputerId")
                                .HasConstraintName("fk_computers_computers_id");
                        });

                    b.OwnsOne("Domain.Computers.CpuId", "CpuId", b1 =>
                        {
                            b1.Property<int>("ComputerId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CpuId");

                            b1.HasKey("ComputerId");

                            b1.ToTable("Computers");

                            b1.WithOwner()
                                .HasForeignKey("ComputerId")
                                .HasConstraintName("fk_computers_computers_id");
                        });

                    b.OwnsOne("Domain.Computers.Disk", "Disk", b1 =>
                        {
                            b1.Property<int>("ComputerId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Serial")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DiskSerial");

                            b1.HasKey("ComputerId");

                            b1.ToTable("Computers");

                            b1.WithOwner()
                                .HasForeignKey("ComputerId")
                                .HasConstraintName("fk_computers_computers_id");
                        });

                    b.OwnsOne("Domain.Computers.MachineGuid", "MachineGuid", b1 =>
                        {
                            b1.Property<int>("ComputerId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MachineGuid");

                            b1.HasKey("ComputerId");

                            b1.ToTable("Computers");

                            b1.WithOwner()
                                .HasForeignKey("ComputerId")
                                .HasConstraintName("fk_computers_computers_id");
                        });

                    b.Navigation("Bios")
                        .IsRequired();

                    b.Navigation("CpuId")
                        .IsRequired();

                    b.Navigation("Disk")
                        .IsRequired();

                    b.Navigation("MachineGuid")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.vault.SecretVersion", b =>
                {
                    b.HasOne("Domain.vault.Secret", null)
                        .WithMany("Versions")
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vault_secret_versions_vault_secrets_secret_id");
                });

            modelBuilder.Entity("Domain.vault.VaultMachine", b =>
                {
                    b.HasOne("Domain.Computers.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vault_machines_computers_computer_id");
                });

            modelBuilder.Entity("Domain.vault.Secret", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
